//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ETrade12Entities : DbContext
    {
        public ETrade12Entities()
            : base("name=ETrade12Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Categoriler> Tbl_Categoriler { get; set; }
        public virtual DbSet<Tbl_Satislar> Tbl_Satislar { get; set; }
        public virtual DbSet<Tbl_Urunler> Tbl_Urunler { get; set; }
    }
}
