//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Satislar
    {
        public int Id { get; set; }
        public string Detay { get; set; }
        public System.DateTime SatisTarihi { get; set; }
        public double Discount { get; set; }
        public int UrunId { get; set; }
    
        public virtual Tbl_Urunler Tbl_Urunler { get; set; }
    }
}
